name: Deploy PR to staging env

on:
  pull_request:
    branches:
    - main

concurrency: ci-${{ github.event.number }}

env:
  WEBAPP_NAME: simple-tomcat-app
  RESOURCE_GROUP: simple-tomcat-app_group
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft

    - name: Build app
      run: mvn clean package

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.war'
  
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    - name: Get app settings from production
      id: get-app-settings
      run: |
        echo "::set-output name=app-settings::$(az webapp config appsettings list --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --query "[?name!='ApplicationInsightsAgent_EXTENSION_VERSION'].{name:name, value:value}" -o tsv)"

    - name: Get app settings from production
      id: get-app-settings
      run: |
        echo "::set-output name=app-settings::$(az webapp config appsettings list --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --query "[].{name:name, value:value}" -o tsv)"

    - name: Set app settings in PR slot
      run: |
        for setting in ${{ steps.get-app-settings.outputs.app-settings }}
        do
          name=$(echo $setting | cut -f1)
          value=$(echo $setting | cut -f2)
          az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --slot $SLOT_NAME --settings "$name=$value"
        done

    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: '*.war'
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'